 #######
1. ansible 서버 ~/.ssh/known_hosts 파일에 node 서버 등록
2. ansible 서버 계정은 admin
3. node 서버는 hosts파일에 미리 기재


---
- hosts: all
  #remote_user: admin
  #become: yes
  #become_method: sudo
  connection: local
  serial: 1
  gather_facts: no

  tasks:
  - command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }}
    register: keyscan

  - lineinfile:
      name=~/.ssh/known_hosts
      create=yes
      line={{ item }}
    with_items:
      - "{{ keyscan.stdout_lines }}"
