# 자동으로 ansible 서버에 node들에 대해 known host에 등록

---
- hosts: all
  #remote_user: admin
  #become: yes
  #become_method: sudo
  connection: local
  serial: 1
  gather_facts: no

  tasks:
  - command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }}   // or  /usr/bin/ssh-keyscan -t rsa {{ ansible_host }}
    register: keyscan
  - lineinfile:
      name=~/.ssh/known_hosts
      create=yes
      line={{ item }}
    with_items:
      - "{{ keyscan.stdout_lines }}"
