# 자동으로 ansible 서버에 node들에 대해 known host에 등록

---
- hosts: all
  connection: local
  serial: 1
  gather_facts: no
  
  tasks:
  - command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }}
    register: keyscan
    
  - lineinfile:
    name=~/.ssh/known_hosts
    create=yes
    line={{ item }}
    with_items:
      - "{{ keyscan.stdout_lines }}"
