---
- name: Install zabbix agent 4.0 for CentOS 6 from repo
  yum:
    name: ftp://172.27.104.9/repo/zabbix/4.0/rhel/6/x86_64/zabbix-agent-4.0.1-1.el6.x86_64.rpm 
    state: present
  become: True
  when:
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
    - ansible_distribution_major_version == "6"

- name: Install zabbix agent 4.0 for CentOS 7 from repo
  yum:
    name: ftp://172.27.104.9/repo/zabbix/4.0/rhel/7/x86_64/zabbix-agent-4.0.1-1.el7.x86_64.rpm 
    state: present
  become: True
  when:
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
    - ansible_distribution_major_version == "7"

- name: Install zabbix get 4.0 for CentOS 6 from repo
  yum:
    name: ftp://172.27.104.9/repo/zabbix/4.0/rhel/6/x86_64/zabbix-get-4.0.1-1.el6.x86_64.rpm 
    state: present
  become: True
  when:
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
    - ansible_distribution_major_version == "6"
  
- name: Install zabbix get 4.0 for CentOS 7 from repo
  yum:
    name: ftp://172.27.104.9/repo/zabbix/4.0/rhel/7/x86_64/zabbix-get-4.0.1-1.el7.x86_64.rpm 
    state: present
  become: True
  when:
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
    - ansible_distribution_major_version == "7"
 
- name: Agent Server config 
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: '^Server='
    line: 'Server=127.0.0.1,172.27.105.206'
  become: True

- name: Agent ServerActive config remove
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    state: absent
    regexp: '^ServerActive='
  become: True

- name: Zabbix disk performance discovery script download
  get_url:
    url: ftp://anonymous:pass@172.27.104.9/repo/zabbix/3.4/rhel/template.d/zabbix-disk-performance-master/lld-disks.py
    dest: /usr/local/bin/lld-disks.py
    mode: 0755
  become: True

- name: Zabbix disk performance parameters config download
  get_url:
    url: ftp://anonymous:pass@172.27.104.9/repo/zabbix/3.4/rhel/template.d/zabbix-disk-performance-master/userparameter_diskstats.conf
    dest: /etc/zabbix/zabbix_agentd.d/userparameter_diskstats.conf
    mode: 0644
  become: True

- name: "change /etc/zabbix/zabbix_agentd.conf > ServerActive "
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: '^# ServerActive='
    line: 'ServerActive=172.27.105.206'
  become: True

- name: "change /etc/zabbix/zabbix_agentd.conf > Hostname "
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: '^Hostname=Zabbix server'
    line: 'Hostname={{ ansible_hostname }}'
  become: True

- name: Agent Remote Command Enable
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: '^# EnableRemoteCommands=0'
    line: 'EnableRemoteCommands=1'
  become: True

- name: " zabbix's agent restart "
  service:
    name: zabbix-agent
    state: restarted
  become: True
