---
# tasks file for open-jdk 11
- name: Packcage java-11-openjdk installed Check
  yum:
    list: java-11-openjdk
  register: pkg-check
  
- name: Install java-11-openjdk
  yum:
    name: java-11-openjdk-devel
    state: present
  when:
    - pkg_check.results | selectattr( "yumstate","match","installed" )|list|length == 0
