## 서버 hosts 그룹 변경 
## 입력값 : 변경을 원하는 계정
## 입력값 : 변수값 (단어와 특수문자)
## 정책 = {변수:단어}{변수:특수문자}{호스트서버 IP 2자리} 
## EX) tiger!34 / circle~34 일 경우 변수는 tiger! 또는 circle~


---
- hosts: dev-linux prd-linux
  remote_user: finadm
  vars:
    ip: '{{ ansible_eth0["ipv4"]["address"] }}'
    ip2: '{{ ansible_bond0["ipv4"]["address"] }}'
    lastnum2: "{{ ip.split('.')[-1][-2:] }}"
    lastnum3: "{{ ip2.split('.')[-1][-2:] }}"
  
  
  vars_prompt:
    - name: "user_id"
      prompt: "Enter the User, you want to change password"
      private: no
    - name: "password var"
      prompt: "Enter the Pawwrod variable"
      private: no
      
  tasks:
  - name: "{{ user_id }} Check if user exists"
    shell: id -u "{{ user_id }}"
    register: user_exists
    ignore_errors: true
    
    
    
