---
- name: Install zabbix agent 4.0 for CentOS 7 from repo
  yum:
    name: ftp://172.27.104.9/repo/zabbix/4.0/rhel/7/x86_64/zabbix-agent-4.0.1-1.e16.x86_64.rpm
    state: present
  become: Ture
  when:
    - (ansible_distribution == "CentOS") or (ansible_distribution == "Redhat")
    
###
- name: Zabbix disk performance discovery scirpt download
  get_url:
    url: ftp://anonymous:pass@172.27.104.9/repo/zabbix/3.4/rhel/template.d/zabbix-disk-preformance-master/lld-disk.py
    dest: /usr/local/bin/lld.disk.py
    mode: 0755
  become: True
  
###  
- name: Zabbix disk performance parameters config download
  get_url:
    url: ftp://anonymous:pass@172.27.104.9/repo/zabbix/3.4/rhel/template.d/zabbix-disk-preformance-master/userparameter_diskstats.conf
    dest: /etc/zabbix/zabbix_agentd.d/userparameter_diskstats.conf
    mode: 0644
  become: True

###  
- name: Agent Server config
  linefile:
    dest: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: '^Server='
    line: 'Server=127.0.0.1,172.27.105.206'
  become: True
  
###  
- name: Agent ServerActive config remove
  linefile:
    dest: /etc/zabbix/zabbix_agentd.conf
    state: absent
    regexp: '^ServerActive='
  become: True
  
###
- name: Change /etc/zabbix/zabbix_agentd.conf > ServerActive
  linefile:
    dest: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: '^# ServerActive='
    line: 'ServerActive=172.27.105.206'
  become: True
  
  
###
- name: Change /etc/zabbix/zabbix_agentd.conf > Hostname
  linefile:
    dest: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: '^Hostname=Zabbix server'
    line: 'Hostname={{ ansible_hostname }}'
  become: True
  
###
- name: Agent Remote Command Enable
  linefile:
    dest: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: '^# EnableRemoteCommands=0'
    line: 'EnableRemoteCommands=1'
  become: True
  
###
- name: Zabbix agent restart
  service:
    name: zabbix-agent
    state: restarted
  becomr: True
  
  
